
nc: 20  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  l: [1.00, 1.00, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [24, 3, 2]]               
  - [-1, 1, nn.MaxPool2d, [3, 2, 1]]
  - [-1, 1, ShuffleV2Stage, [48, 4]]  # p1 2
  - [-1, 1, ShuffleV2Stage, [96, 8]]  # p2 3
  - [-1, 1, ShuffleV2Stage, [192, 4]] # p3 4
  - [-1, 1, SPPF, [192, 5]]  # 5

head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 3], 1, Concat, [1]]  # cat backbone P4
  # - [-1, 3, C2f, [96]]
  - [-1, 1, ShuffleV2Stage, [96, 2, True]]  # 8

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P3
  # - [-1, 3, C2f, [48]]
  - [-1, 1, ShuffleV2Stage, [48, 2, True]]  # 11

  - [-1, 1, Conv, [48, 3, 2]]
  - [[-1, 8], 1, Concat, [1]]  # cat head P4
  # - [-1, 3, C2f, [96]]
  - [-1, 1, ShuffleV2Stage, [96, 2, True]]  # 14

  - [-1, 1, Conv, [96, 3, 2]]
  - [[-1, 5], 1, Concat, [1]]  # cat head P5
  # - [-1, 3, C2f, [192]]
  - [-1, 1, ShuffleV2Stage, [192, 2, True]]  # 17

  - [[11, 14, 17], 1, Detect, [nc]]  # Detect(P3, P4, P5)
